package entities;
// Generated Jan 27, 2016 6:15:22 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Lokhoan generated by hbm2java
 */
public class Lokhoan  implements java.io.Serializable {


     private int gid;
     private String wellname;
     private String block;
     private String basin;
     private String structure;
     private String class_;
     private String result;
     private String operator;
     private String contractor;
     private String status;
     private Date startDate;
     private Date tdDate;
     private Date finishDat;
     private BigDecimal waterDept;
     private BigDecimal platHeigh;
     private String remark;
     private String platform;
     private String platType;
     private String bottom;
     private BigDecimal longitude;
     private BigDecimal latitude;
     private Serializable geom;

    public Lokhoan() {
    }

	
    public Lokhoan(int gid) {
        this.gid = gid;
    }
    public Lokhoan(int gid, String wellname, String block, String basin, String structure, String class_, String result, String operator, String contractor, String status, Date startDate, Date tdDate, Date finishDat, BigDecimal waterDept, BigDecimal platHeigh, String remark, String platform, String platType, String bottom, BigDecimal longitude, BigDecimal latitude, Serializable geom) {
       this.gid = gid;
       this.wellname = wellname;
       this.block = block;
       this.basin = basin;
       this.structure = structure;
       this.class_ = class_;
       this.result = result;
       this.operator = operator;
       this.contractor = contractor;
       this.status = status;
       this.startDate = startDate;
       this.tdDate = tdDate;
       this.finishDat = finishDat;
       this.waterDept = waterDept;
       this.platHeigh = platHeigh;
       this.remark = remark;
       this.platform = platform;
       this.platType = platType;
       this.bottom = bottom;
       this.longitude = longitude;
       this.latitude = latitude;
       this.geom = geom;
    }
   
    public int getGid() {
        return this.gid;
    }
    
    public void setGid(int gid) {
        this.gid = gid;
    }
    public String getWellname() {
        return this.wellname;
    }
    
    public void setWellname(String wellname) {
        this.wellname = wellname;
    }
    public String getBlock() {
        return this.block;
    }
    
    public void setBlock(String block) {
        this.block = block;
    }
    public String getBasin() {
        return this.basin;
    }
    
    public void setBasin(String basin) {
        this.basin = basin;
    }
    public String getStructure() {
        return this.structure;
    }
    
    public void setStructure(String structure) {
        this.structure = structure;
    }
    public String getClass_() {
        return this.class_;
    }
    
    public void setClass_(String class_) {
        this.class_ = class_;
    }
    public String getResult() {
        return this.result;
    }
    
    public void setResult(String result) {
        this.result = result;
    }
    public String getOperator() {
        return this.operator;
    }
    
    public void setOperator(String operator) {
        this.operator = operator;
    }
    public String getContractor() {
        return this.contractor;
    }
    
    public void setContractor(String contractor) {
        this.contractor = contractor;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getTdDate() {
        return this.tdDate;
    }
    
    public void setTdDate(Date tdDate) {
        this.tdDate = tdDate;
    }
    public Date getFinishDat() {
        return this.finishDat;
    }
    
    public void setFinishDat(Date finishDat) {
        this.finishDat = finishDat;
    }
    public BigDecimal getWaterDept() {
        return this.waterDept;
    }
    
    public void setWaterDept(BigDecimal waterDept) {
        this.waterDept = waterDept;
    }
    public BigDecimal getPlatHeigh() {
        return this.platHeigh;
    }
    
    public void setPlatHeigh(BigDecimal platHeigh) {
        this.platHeigh = platHeigh;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    public String getPlatform() {
        return this.platform;
    }
    
    public void setPlatform(String platform) {
        this.platform = platform;
    }
    public String getPlatType() {
        return this.platType;
    }
    
    public void setPlatType(String platType) {
        this.platType = platType;
    }
    public String getBottom() {
        return this.bottom;
    }
    
    public void setBottom(String bottom) {
        this.bottom = bottom;
    }
    public BigDecimal getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }
    public BigDecimal getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }
    public Serializable getGeom() {
        return this.geom;
    }
    
    public void setGeom(Serializable geom) {
        this.geom = geom;
    }




}


