package entities;
// Generated Jan 27, 2016 6:15:22 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * Thuadat12457 generated by hbm2java
 */
public class Thuadat12457  implements java.io.Serializable {


     private int gid;
     private Integer id;
     private Double thuaid;
     private Integer xaid;
     private Integer shbando;
     private Integer shthua;
     private Double dientich;
     private Double dientichpl;
     private Integer maloaidat;
     private String khloaidat;
     private String diadanh;
     private Integer dtsd;
     private String tenchu;
     private String diachi;
     private Integer mdsd2003;
     private String kh2003;
     private Integer mscolor;
     private String shthuatam;
     private String dtthocu;
     private Serializable theGeom;

    public Thuadat12457() {
    }

	
    public Thuadat12457(int gid) {
        this.gid = gid;
    }
    public Thuadat12457(int gid, Integer id, Double thuaid, Integer xaid, Integer shbando, Integer shthua, Double dientich, Double dientichpl, Integer maloaidat, String khloaidat, String diadanh, Integer dtsd, String tenchu, String diachi, Integer mdsd2003, String kh2003, Integer mscolor, String shthuatam, String dtthocu, Serializable theGeom) {
       this.gid = gid;
       this.id = id;
       this.thuaid = thuaid;
       this.xaid = xaid;
       this.shbando = shbando;
       this.shthua = shthua;
       this.dientich = dientich;
       this.dientichpl = dientichpl;
       this.maloaidat = maloaidat;
       this.khloaidat = khloaidat;
       this.diadanh = diadanh;
       this.dtsd = dtsd;
       this.tenchu = tenchu;
       this.diachi = diachi;
       this.mdsd2003 = mdsd2003;
       this.kh2003 = kh2003;
       this.mscolor = mscolor;
       this.shthuatam = shthuatam;
       this.dtthocu = dtthocu;
       this.theGeom = theGeom;
    }
   
    public int getGid() {
        return this.gid;
    }
    
    public void setGid(int gid) {
        this.gid = gid;
    }
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Double getThuaid() {
        return this.thuaid;
    }
    
    public void setThuaid(Double thuaid) {
        this.thuaid = thuaid;
    }
    public Integer getXaid() {
        return this.xaid;
    }
    
    public void setXaid(Integer xaid) {
        this.xaid = xaid;
    }
    public Integer getShbando() {
        return this.shbando;
    }
    
    public void setShbando(Integer shbando) {
        this.shbando = shbando;
    }
    public Integer getShthua() {
        return this.shthua;
    }
    
    public void setShthua(Integer shthua) {
        this.shthua = shthua;
    }
    public Double getDientich() {
        return this.dientich;
    }
    
    public void setDientich(Double dientich) {
        this.dientich = dientich;
    }
    public Double getDientichpl() {
        return this.dientichpl;
    }
    
    public void setDientichpl(Double dientichpl) {
        this.dientichpl = dientichpl;
    }
    public Integer getMaloaidat() {
        return this.maloaidat;
    }
    
    public void setMaloaidat(Integer maloaidat) {
        this.maloaidat = maloaidat;
    }
    public String getKhloaidat() {
        return this.khloaidat;
    }
    
    public void setKhloaidat(String khloaidat) {
        this.khloaidat = khloaidat;
    }
    public String getDiadanh() {
        return this.diadanh;
    }
    
    public void setDiadanh(String diadanh) {
        this.diadanh = diadanh;
    }
    public Integer getDtsd() {
        return this.dtsd;
    }
    
    public void setDtsd(Integer dtsd) {
        this.dtsd = dtsd;
    }
    public String getTenchu() {
        return this.tenchu;
    }
    
    public void setTenchu(String tenchu) {
        this.tenchu = tenchu;
    }
    public String getDiachi() {
        return this.diachi;
    }
    
    public void setDiachi(String diachi) {
        this.diachi = diachi;
    }
    public Integer getMdsd2003() {
        return this.mdsd2003;
    }
    
    public void setMdsd2003(Integer mdsd2003) {
        this.mdsd2003 = mdsd2003;
    }
    public String getKh2003() {
        return this.kh2003;
    }
    
    public void setKh2003(String kh2003) {
        this.kh2003 = kh2003;
    }
    public Integer getMscolor() {
        return this.mscolor;
    }
    
    public void setMscolor(Integer mscolor) {
        this.mscolor = mscolor;
    }
    public String getShthuatam() {
        return this.shthuatam;
    }
    
    public void setShthuatam(String shthuatam) {
        this.shthuatam = shthuatam;
    }
    public String getDtthocu() {
        return this.dtthocu;
    }
    
    public void setDtthocu(String dtthocu) {
        this.dtthocu = dtthocu;
    }
    public Serializable getTheGeom() {
        return this.theGeom;
    }
    
    public void setTheGeom(Serializable theGeom) {
        this.theGeom = theGeom;
    }




}


